In [1]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import pandas as pd
import re

In [2]:
nRowsRead = None
df1 = pd.read_csv('C:\\Users\\imvla\\ZalidQomalita\\Job\\3. Script\\2024\\Sosmed\\dataset_artikel\\artikel_alwi.csv', delimiter=',', nrows = nRowsRead)

nRow, nCol = df1.shape
df1.drop(columns=['Judul'],inplace=True)
print(f'Ada {nRow} baris dan {nCol} kolom')

Ada 50 baris dan 3 kolom


In [37]:
df1

Bidang                                                Isi
0     Ekonomi  Pemerintah optimistis ekonomi Indonesia akan t...
1     Ekonomi  Mandiri Investment Forum 2021 yang akan berlan...
2     Ekonomi  PT Bank Mandiri Tbk memprediksi bahwa pertumbu...
3     Ekonomi  Pemulihan ekonomi Indonesia diprediksi terjadi...
4     Ekonomi  Menteri Perindustrian (Menperin) Agus Gumiwang...
5     Ekonomi  Gubernur Bank Indonesia (BI) Perry Warjiyo mem...
6     Ekonomi  Presiden Joko Widodo (Jokowi) berkomitmen untu...
7     Ekonomi  Penemuan vaksin covid-19 menjadi kunci pemulih...
8     Ekonomi  Dalam forum internasional, Menteri Keuangan Sr...
9     Ekonomi  Direktur Jenderal Perhubungan Darat Kementeria...
10  Teknologi  Setahun berlalu sejak pandemi virus Covid-19 m...
11  Teknologi  NASA berencana mendaratkan manusia di Planet M...
12  Teknologi  Tuntutan mobilitas serta migrasi aplikasi dan ...
13  Teknologi  Awal tahun menjadi momen tak terlupakan oleh p...
14  Teknologi  PasarPolis berkomitmen bisa membuka peluang ga...
15  Teknologi  Berkembangnya teknologi digital dan akses info...
16  Teknologi  CEO Apple Tim Cook secara tidak langsung menyi...
17  Teknologi  Teknologi yang berkembang di dunia otomotif ti...
18  Teknologi  Mobil listrik menjadi isu paling menarik belak...
19  Teknologi  Terobosan demi terobosan terus dihadirkan oleh...
20      Hukum  Dewan Perwakilan Rakyat Amerika Serikat memili...
21      Hukum  Polda NTT mulai menyelidiki kasus kewarganegar...
22      Hukum  Jaksa di Kejari Kuansing, Riau, menahan dua pe...
23      Hukum  Pakar hukum Tindak Pidana Pencucian Uang (TPPU...
24      Hukum  Kasus siswi nonmuslim di SMK Negeri 2 kota Pad...
25      Hukum  Mantan vokalis Kerispatih, Sammy Simorangkir, ...
26      Hukum  Perdana Menteri Thailand, Prayuth Chan-ocha, p...
27      Hukum  Pakar Hukum Tindak Pidana Pencucian Uang (TPPU...
28      Hukum  Fraksi PKB di DPR RI mengusulkan agar RUU Peng...
29      Hukum  Kerajaan Arab Saudi merilis aturan untuk mengu...
30     Sosial  Sebanyak 500 penerima manfaat di Tambora, Jaka...
31     Sosial  Interaksi langsung yang jauh menurun demi mena...
32     Sosial  Ketua Umum Asosiasi Peternak Layer Nasional, K...
33     Sosial  Anak-anak dari segala usia dapat sepenuhnya me...
34     Sosial  Menteri Priwisata dan Ekonomi Kreatif Sandiaga...
35     Sosial  Sub Direktorat Pengendalian Konten Internet Di...
36     Sosial  Sejak pandemi Covid-19 melanda Indonesia sejak...
37     Sosial  Petugas gabungan dari unsur Satpol PP, TNI dan...
38     Sosial  Presiden Joko Widodo (Jokowi) membuka opsi pem...
39     Sosial  Kesenjangan rasial dalam kasus kematian Covid-...
40  Kesehatan  Gubernur Jawa Timur Khofifah Indar Parawansa m...
41  Kesehatan  Pemerintah Kalimantan Timur membatasi aktivita...
42  Kesehatan  Sebanyak 8.150 tenaga kesehatan di Kota Malang...
43  Kesehatan  Di tengah lonjakan kasus COVID-19 di Indonesia...
44  Kesehatan  Satuan Tugas (Satgas) Penanganan COVID-19 Prov...
45  Kesehatan  Wakil Gubernur DKI Jakarta Ahmad Riza Patria m...
46  Kesehatan  Presiden Joko Widodo atau Jokowi menyampaikan ...
47  Kesehatan  Menteri Kesehatan (Menkes) Budi Gunadi Sadikin...
48  Kesehatan  Juru Bicara Satuan Tugas Penanganan COVID-19 W...
49  Kesehatan  Pemerintah Provinsi Jawa Barat berencana mengg...

In [9]:
df1['Bidang'].value_counts()

Bidang
Ekonomi      10
Teknologi    10
Hukum        10
Sosial       10
Kesehatan    10
Name: count, dtype: int64

In [4]:
#Data Kedua
df2 = pd.read_csv('C:\\Users\\imvla\\ZalidQomalita\\Job\\3. Script\\2024\\Sosmed\\dataset_artikel\\sentences.csv', delimiter=',', nrows = nRowsRead)

nRow, nCol = df2.shape
print(f'Ada {nRow} baris dan {nCol} kolom')

Ada 887 baris dan 2 kolom


In [10]:
df2['kategori_teks'].value_counts()

kategori_teks
ekonomi      231
politik      229
hiburan      227
kesehatan    200
Name: count, dtype: int64

In [38]:
# DATASET 3

nRowsRead = None
df3 = pd.read_excel('C:\\Users\\imvla\\ZalidQomalita\\Job\\3. Script\\2024\\Sosmed\\OpenData.xlsx') 

nRow, nCol = df3.shape
print(f'Ada {nRow} baris dan {nCol} kolom')
df3['Bidang'].value_counts()

Ada 1460 baris dan 2 kolom


Bidang
sosial                       279
pendidikan                   274
kependudukan                 242
administrasi pemerintahan    232
lingkungan hidup             229
infrastruktur                204
Name: count, dtype: int64

In [51]:
#DATASET 4  : https://github.com/andreaschandra/indonesian-news
import pickle

files = "C:\\Users\\imvla\\ZalidQomalita\\Job\\3. Script\\2024\\Sosmed\\training.res"
data4 = pickle.load(open(files, 'rb'))
d4 = pd.DataFrame({'content': data4[0], 'label': data4[1]})
tekno = d4[d4['label']=='tekno']
tekno = tekno[:287]
tekno['label']='teknologi'
df_tekno = pd.concat([tekno['label'],tekno['content']],axis=1)
df_tekno.columns = ['Bidang','Isi']
df_tekno


Bidang                                                Isi
15    teknologi  Liputan6.com, Jakarta - Bos Amazon Jeff Bezos ...
21    teknologi  Liputan6.com, Jakarta - Gojek mengapresiasi Un...
25    teknologi  Liputan6.com, Jakarta Setiap handphone pasti m...
29    teknologi  Liputan6.com, Jakarta - PT Pasifik Satelit Nus...
31    teknologi  Liputan6.com, Jakarta Samsung, brand ternama a...
...         ...                                                ...
2917  teknologi  Liputan6.com, Jakarta - Sejumlah aplikasi-apli...
2920  teknologi  Liputan6.com, Jakarta - Electronic Arts baru s...
2921  teknologi  Liputan6.com, Jakarta - Lolos babak kualifikas...
2933  teknologi  Liputan6.com, Jakarta - Warganet Indonesia sea...
2934  teknologi  Liputan6.com, Jakarta - Android tak dimungkiri...

[287 rows x 2 columns]

In [49]:
#dataset 5
df5_read = pd.read_json("hf://datasets/biznetgio/indonesia-law-qa-embeddings/embedings.json")
df5 = df5_read[['summarize']].copy()
df5['Bidang'] = 'hukum'
df5[:287]


summarize Bidang
0    Girik bukanlah tanda bukti atas tanah, tetapi ...  hukum
1    \nSaat ini, kedudukan dan legal standing paral...  hukum
2    Penggelapan merupakan delik biasa yang tidak m...  hukum
3    Pengusaha mempekerjakan pekerja/buruh melebihi...  hukum
4    \nDalam hal seorang polisi berada di club mala...  hukum
..                                                 ...    ...
282  Remisi atau pengurangan menjalani masa pidana ...  hukum
283  Anggaran Pendapatan dan Belanja Negara (“APBN”...  hukum
284  Pada intinya, di Indonesia terdapat asas kepem...  hukum
285  Pemagangan dilakukan dengan perjanjian tertuli...  hukum
286  Hak warga negara adalah hak khusus yang diberi...  hukum

[287 rows x 2 columns]

In [50]:
df5 = df5[:288]
df5_ = pd.concat([df5['Bidang'],df5['summarize']],axis=1)
df5_.columns = ['Bidang','Isi']
df5_

Bidang                                                Isi
0    hukum  Girik bukanlah tanda bukti atas tanah, tetapi ...
1    hukum  \nSaat ini, kedudukan dan legal standing paral...
2    hukum  Penggelapan merupakan delik biasa yang tidak m...
3    hukum  Pengusaha mempekerjakan pekerja/buruh melebihi...
4    hukum  \nDalam hal seorang polisi berada di club mala...
..     ...                                                ...
283  hukum  Anggaran Pendapatan dan Belanja Negara (“APBN”...
284  hukum  Pada intinya, di Indonesia terdapat asas kepem...
285  hukum  Pemagangan dilakukan dengan perjanjian tertuli...
286  hukum  Hak warga negara adalah hak khusus yang diberi...
287  hukum  \nPerlu diketahui bahwa perkawinan haruslah di...

[288 rows x 2 columns]

In [43]:
def remove_df_special(text):
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"").replace('\xa0'," ").replace("\"","")
    text = text.lower()
    text = ''.join([i for i in text if not i.isdigit()])
    text = text[:200]
    return text.replace("http://", " ").replace("https://", " ")

In [42]:
df_temp = pd.concat([df2['kategori_teks'],df2['kalimat']],axis=1)
df_temp.columns = ['Bidang','Isi']
df_temp

Bidang                                                Isi
0    kesehatan  “12 puskesmas di Sukoharjo telah memiliki klin...
1    kesehatan  "Ada kemungkinan masa rehatnya itu akan panjan...
2    kesehatan  "Adapun penyebab kematiannya adalah air mendid...
3    kesehatan  "Ada empat orang yang akan membesuk ke rumah s...
4    kesehatan      “Ada tempat-tempat yang tidak boleh merokok."
..         ...                                                ...
882    hiburan  Kang Seung-yoon mengunggah foto nasi goreng de...
883    hiburan  Karena itu kami ingin melalui musik Indonesia ...
884    hiburan  Karena kehebohan itu, banyak yang penasaran de...
885    hiburan            Kebahagiaan akan muncul dari anak-anak.
886    hiburan  Lokasi ini akan menjadi destinasi wisata tujua...

[887 rows x 2 columns]

In [52]:
df = pd.concat([df1,df_temp,df3,df_tekno,df5_],axis=0)
df['bidang']=df['Bidang'].apply(remove_df_special)
df['isi'] = df['Isi'].apply(remove_df_special)
df.drop(columns=['Bidang', 'Isi'],inplace=True)
df.drop_duplicates(subset=['isi'])
df.head()

bidang                                                isi
0  ekonomi  pemerintah optimistis ekonomi indonesia akan t...
1  ekonomi  mandiri investment forum  yang akan berlangsun...
2  ekonomi  pt bank mandiri tbk memprediksi bahwa pertumbu...
3  ekonomi  pemulihan ekonomi indonesia diprediksi terjadi...
4  ekonomi  menteri perindustrian (menperin) agus gumiwang...

In [53]:
df['bidang'].value_counts()

bidang
hukum                        298
teknologi                    297
sosial                       289
pendidikan                   274
kependudukan                 242
ekonomi                      241
administrasi pemerintahan    232
politik                      229
lingkungan hidup             229
hiburan                      227
kesehatan                    210
infrastruktur                204
Name: count, dtype: int64

In [54]:
# import torch and Huggingface dependencies
from transformers import AutoModel, AutoTokenizer
import torch.nn as nn
import torch

In [56]:

class model(nn.Module):
    def __init__(self, checkpoint, freeze=False, device='cpu'):
        super().__init__()
        
        self.model = AutoModel.from_pretrained(checkpoint)
        hidden_sz = self.model.config.hidden_size
        # set device cuda or cpu
        self.device = device
        # freeze model
        if freeze:
            for layer in self.model.parameters():
                layer.requires_grad=False
        
    def forward(self, x, attention_mask=None):
            
        x = x.to(self.device)
        # pooler_output(seq,dim) 
        with torch.no_grad():
            model_out = self.model(x['input_ids'], x['attention_mask'], return_dict=True)
            
        embds = model_out.last_hidden_state # model_out[0][:,0]
        mean_pool = embds.sum(axis=1)/ x['attention_mask'].sum(axis=1).unsqueeze(axis=1)
        return mean_pool

In [57]:
checkpoint = 'indolem/indobertweet-base-uncased'
indobert = model(checkpoint, freeze=True)

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [58]:
docs = list( df['isi'])
label = list( df['bidang'])

In [59]:
# dataloader
final_embeddings =list()
all_embeddings = []

final_sentences = docs

batch_sz = 200 # batch_size
for idx in range(0, len(final_sentences), batch_sz):
    batch_sentences = final_sentences[idx:idx+batch_sz]
    for sent in batch_sentences:
        tokens = tokenizer(sent ,truncation='longest_first', return_tensors='pt', return_attention_mask=True,padding=True)
        embeddings = indobert(tokens)
        final_embeddings.extend(embeddings)
        all_embeddings = torch.stack(final_embeddings)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


# KLASIFIKASI

In [60]:
from sklearn.model_selection import train_test_split
labels=df['bidang'].map({'ekonomi':1, 'teknologi':2, 'hukum':3, 'sosial':4, 'kesehatan':5, 'politik': 6, 'hiburan':7,'kependudukan':8, 'lingkungan hidup':9, 'infrastruktur':10, 'pendidikan':11, 'administrasi pemerintahan':12 })  
x_train, x_val, y_train, y_val = train_test_split(pd.DataFrame(all_embeddings),labels,test_size=0.2,random_state=1, stratify = labels)

print("jml training ",len(x_train),"jml test ",len(x_val))

jml training  2377 jml test  595


In [61]:
#Support Vector Machine (SVM) classifier with OvR strategy
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm_ovr_model = SVC(kernel='linear', C=1, decision_function_shape='ovo', random_state=1)
svm_ovr_model.fit(x_train, y_train.values.ravel())
prediction_ovr = svm_ovr_model.predict(x_val)

akurasiNN_train = svm_ovr_model.score(x_train,y_train)
akurasiNN = svm_ovr_model.score(x_val,y_val)

print('   |akurasi train   = ',akurasiNN_train,'   |akurasi test     = ',akurasiNN)


   |akurasi train   =  1.0    |akurasi test     =  0.9109243697478991


In [62]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,prediction_ovr)

array([[42,  2,  0,  0,  1,  3,  0,  0,  0,  0,  0,  0],
       [ 0, 60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 59,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0, 53,  0,  0,  0,  0,  1,  0,  0,  2],
       [ 1,  0,  0,  0, 35,  1,  5,  0,  0,  0,  0,  0],
       [ 4,  1,  4,  0,  1, 34,  2,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  1,  0, 42,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0, 44,  0,  0,  1,  2],
       [ 0,  0,  0,  1,  0,  0,  0,  0, 44,  1,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  1, 35,  1,  1],
       [ 0,  0,  0,  1,  0,  2,  1,  0,  0,  0, 51,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  1,  0,  0,  0, 43]], dtype=int64)

In [63]:
from sklearn.neural_network import MLPClassifier

#Neural Network -------------------------------------------
hl = [[50,50],[80,80],[100,100],[120,120]]
lr = [0.00005, 0.0005, 0.001, 0.01]

for x in hl:
    print('Hidden layer  = ',x)
    for y in lr:
        modelNN = MLPClassifier(max_iter=1500, activation='relu',random_state=1, batch_size = 128, hidden_layer_sizes=x, learning_rate_init=y).fit(x_train,y_train.values.ravel())
        predNN = modelNN.predict(x_val)
        akurasiNN_train = modelNN.score(x_train,y_train)
        akurasiNN = modelNN.score(x_val,y_val)
        print('Learning rate = ',y,'   |akurasi train   = ',akurasiNN_train,'   |akurasi test     = ',akurasiNN)

Hidden layer  =  [50, 50]
Learning rate =  5e-05    |akurasi train   =  1.0    |akurasi test     =  0.9092436974789916
Learning rate =  0.0005    |akurasi train   =  1.0    |akurasi test     =  0.9159663865546218
Learning rate =  0.001    |akurasi train   =  1.0    |akurasi test     =  0.9042016806722689
Learning rate =  0.01    |akurasi train   =  1.0    |akurasi test     =  0.9092436974789916
Hidden layer  =  [80, 80]
Learning rate =  5e-05    |akurasi train   =  1.0    |akurasi test     =  0.9109243697478991
Learning rate =  0.0005    |akurasi train   =  1.0    |akurasi test     =  0.9058823529411765
Learning rate =  0.001    |akurasi train   =  1.0    |akurasi test     =  0.9058823529411765
Learning rate =  0.01    |akurasi train   =  1.0    |akurasi test     =  0.9109243697478991
Hidden layer  =  [100, 100]
Learning rate =  5e-05    |akurasi train   =  1.0    |akurasi test     =  0.9176470588235294
Learning rate =  0.0005    |akurasi train   =  1.0    |akurasi test     =  0.909243

In [65]:
#Pilih Model terbaik Neural Network
#Berdasarkan percobaan diatas, learning rate = 0.001 dan hidden layer =[120,120] menghasilkan rata-rata akurasi tertinggi
from sklearn.metrics import confusion_matrix
mNN = MLPClassifier(max_iter=1500, activation='relu',random_state=1, hidden_layer_sizes=[120,120], learning_rate_init=0.001).fit(x_train,y_train.values.ravel())
predNN = mNN.predict(x_val)
accuracyHONN_train = mNN.score(x_train,y_train)
accuracyHONN = mNN.score(x_val,y_val)
print('akurasi Holdout - Neural Network TRAIN = ',accuracyHONN_train)
print('akurasi Holdout - Neural Network TEST = ',accuracyHONN)
cmNN = confusion_matrix(y_val,predNN)
print('confusion matrik test :')
print(cmNN)

akurasi Holdout - Neural Network TRAIN =  1.0
akurasi Holdout - Neural Network TEST =  0.9142857142857143
confusion matrik test :
[[41  1  0  0  1  4  1  0  0  0  0  0]
 [ 0 60  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 59  0  1  0  0  0  0  0  0  0]
 [ 0  2  0 53  1  0  0  0  1  0  1  0]
 [ 1  1  1  0 36  0  3  0  0  0  0  0]
 [ 3  1  3  0  0 36  3  0  0  0  0  0]
 [ 0  2  0  0  1  0 42  0  0  0  0  0]
 [ 0  0  0  1  0  1  0 43  0  0  1  2]
 [ 0  0  0  1  0  0  0  0 44  1  0  0]
 [ 0  0  0  3  0  0  0  0  0 37  1  0]
 [ 0  0  0  1  0  2  1  0  0  0 51  0]
 [ 0  0  0  3  0  0  0  1  0  0  0 42]]


In [66]:
import joblib
joblib.dump(mNN,'model_topik_new.pkl')

['model_topik_new.pkl']

In [67]:
import joblib
model_load = joblib.load('model_topik_new.pkl')

In [68]:
checkpoint = 'indolem/indobertweet-base-uncased'
indobert = model(checkpoint, freeze=True)
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
kata = "BUDAYA membaca adalah kebiasaan atau pola perilaku dalam membaca yang diterapkan secara luas dalam suatu masyarakat. Budaya ini penting karena berperan besar dalam pengembangan intelektual individu dan kemajuan bangsa. Di era informasi dan digital saat ini, membaca tidak hanya terbatas pada buku cetak, tetapi juga mencakup media digital seperti e-book, artikel online, dan media sosial. Tentu ada banyak manfaatnya. Pertama, meningkatkan pengetahuan: Membaca membuka akses pada informasi dan ilmu pengetahuan yang membantu individu memahami dunia secara lebih luas."

In [69]:
# dataloader
final_embeddings =list()
all_embeddings = []

final_sentences = [kata]

batch_sz = 200 # batch_size
for idx in range(0, len(final_sentences), batch_sz):
    batch_sentences = final_sentences[idx:idx+batch_sz]
    for sent in batch_sentences:
        tokens = tokenizer(sent ,truncation='longest_first', return_tensors='pt', return_attention_mask=True,padding=True)
        embeddings = indobert(tokens)
        final_embeddings.extend(embeddings)
        all_embeddings = torch.stack(final_embeddings)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [70]:
model_load.predict(pd.DataFrame(all_embeddings))

array([2], dtype=int64)